name: Export KiCAD schematics

on:
  push:
    paths:
    - '**.sch'
    - '**.kicad_pcb'
  pull_request:
    paths:
      - '**.sch'
      - '**.kicad_pcb'

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: nerdyscout/kicad-exports@v2.2
      with:
      # Required - kibot config file
        config: docs.kibot.yaml
        dir: docs
        schema: '*.sch'
        board: '*.kicad_pcb'
        
    - name: upload results
      uses: actions/upload-artifact@v2
      with:
        name: docs
        path: docs